
server:
  port: 8085

spring:
  application:
    name: config-single-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MapMode/cloud-config #配置文件所在仓库
          username: xiechaog@gmail.com
          password: xiechao981547
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录